### ISSUE TITLE
How to extract depth and color images

### ISSUE THREAD

**Issue by hoangcuongbk80** [hkust-vgd/scenenn#13]
Hi,

I am using Ubuntu 16.04, however I couldn't find the MakeFile in the playback folder.
Could you check the folder playback in the [link](http://103.24.77.34:8080/scenenn/main/tools/).
@songuke It would be great if you could give me some suggestion as soon as possible, I have something urgent that needs to use your dataset. Thank you in advance!

**Comment by songuke** [comment]
Could you check the Makefile at this repository?
https://github.com/hkust-vgd/scenenn/tree/master/playback

Thanks.

2019年12月6日(金) 18:37 Hoang Dinh Cuong <notifications@github.com>:

**Comment by hoangcuongbk80** [comment]
Thank you very much for your quick reply!
